version: '3'

services:
  agranel_postgres:
    image: postgres
    container_name: agranel_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  agranel_pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "4000:80"
    depends_on:
      - agranel_postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
