version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "bruno"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "agraneldb"
    ports:
      - "5432:5432"
    volumes:
      - /home/bruno/dev/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bruno@moreira.com"
      PGADMIN_DEFAULT_PASSWORD: "dev"
    ports:
      - "4000:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
